# Generated by Django 5.0.6 on 2024-05-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='txnomeevento')),
                ('description', models.CharField(max_length=512, null=True, verbose_name='txdescricaoevento')),
                ('initial_date', models.DateField(verbose_name='dtinicialevento')),
                ('final_date', models.DateField(verbose_name='dtfinalevento')),
                ('initial_hour', models.TimeField(verbose_name='hrinicialevento')),
                ('final_hour', models.TimeField(verbose_name='hrfinalevento')),
                ('min_participants', models.IntegerField(null=True, verbose_name='numinimoparticipante')),
                ('max_participants', models.IntegerField(null=True, verbose_name='numaximoparticipante')),
                ('num_participants', models.IntegerField(null=True, verbose_name='nuparticipantes')),
                ('enrollment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='vlinscricaoevento')),
                ('location', models.TextField(verbose_name='txlocalevento')),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
    ]
