# Generated by Django 5.0.6 on 2024-06-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='min_participants',
        ),
    ]
