# Generated by Django 5.0.6 on 2024-06-17 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0001_initial'),
        ('event', '0003_alter_events_num_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_organizer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autentication.organizer'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='event_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.events'),
        ),
    ]
